import type { FontWeight, TypographyVariants } from './Type';
import { foundationTypography } from './FoundationToken';
import { baseTypographyToken } from './BaseTypographyToken';

export const TYPOGRAPHY_STYLES: TypographyVariants = {
  display1Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.display.display1.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.display.display1.lineHeight,
  },
  display1Heavy: {
    fontFamily: foundationTypography.fontFamily.latoHeavy,
    fontSize: baseTypographyToken.display.display1.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightHeavy as FontWeight,
    lineHeight: baseTypographyToken.display.display1.lineHeight,
  },
  display1Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.display.display1.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.display.display1.lineHeight,
  },
  display2Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.display.display2.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.display.display2.lineHeight,
  },
  display2Heavy: {
    fontFamily: foundationTypography.fontFamily.latoHeavy,
    fontSize: baseTypographyToken.display.display2.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightHeavy as FontWeight,
    lineHeight: baseTypographyToken.display.display2.lineHeight,
  },
  display2Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.display.display2.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.display.display2.lineHeight,
  },
  display3Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.display.display3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.display.display3.lineHeight,
  },
  display3Heavy: {
    fontFamily: foundationTypography.fontFamily.latoHeavy,
    fontSize: baseTypographyToken.display.display3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightHeavy as FontWeight,
    lineHeight: baseTypographyToken.display.display3.lineHeight,
  },
  display3Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.display.display3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.display.display3.lineHeight,
  },
  display4Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.display.display4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.display.display4.lineHeight,
  },
  display4Heavy: {
    fontFamily: foundationTypography.fontFamily.latoHeavy,
    fontSize: baseTypographyToken.display.display4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightHeavy as FontWeight,
    lineHeight: baseTypographyToken.display.display4.lineHeight,
  },
  display4Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.display.display4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.display.display4.lineHeight,
  },
  heading1Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.heading.heading1.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.heading.heading1.lineHeight,
  },
  heading1Heavy: {
    fontFamily: foundationTypography.fontFamily.latoHeavy,
    fontSize: baseTypographyToken.heading.heading1.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightHeavy as FontWeight,
    lineHeight: baseTypographyToken.heading.heading1.lineHeight,
  },
  heading2Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.heading.heading2.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.heading.heading2.lineHeight,
  },
  heading2Heavy: {
    fontFamily: foundationTypography.fontFamily.latoHeavy,
    fontSize: baseTypographyToken.heading.heading2.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightHeavy as FontWeight,
    lineHeight: baseTypographyToken.heading.heading2.lineHeight,
  },
  heading3Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.heading.heading3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.heading.heading3.lineHeight,
  },
  heading3Heavy: {
    fontFamily: foundationTypography.fontFamily.latoHeavy,
    fontSize: baseTypographyToken.heading.heading3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightHeavy as FontWeight,
    lineHeight: baseTypographyToken.heading.heading3.lineHeight,
  },
  heading3Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.heading.heading3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.heading.heading3.lineHeight,
  },
  heading4Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.heading.heading4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.heading.heading4.lineHeight,
  },
  heading4Heavy: {
    fontFamily: foundationTypography.fontFamily.latoHeavy,
    fontSize: baseTypographyToken.heading.heading4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightHeavy as FontWeight,
    lineHeight: baseTypographyToken.heading.heading4.lineHeight,
  },
  heading4Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.heading.heading4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.heading.heading4.lineHeight,
  },
  heading5Black: {
    fontFamily: foundationTypography.fontFamily.latoBlack,
    fontSize: baseTypographyToken.heading.heading5.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBlack as FontWeight,
    lineHeight: baseTypographyToken.heading.heading5.lineHeight,
  },
  heading5Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.heading.heading5.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.heading.heading5.lineHeight,
  },
  heading5Medium: {
    fontFamily: foundationTypography.fontFamily.latoMedium,
    fontSize: baseTypographyToken.heading.heading5.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightMedium as FontWeight,
    lineHeight: baseTypographyToken.heading.heading5.lineHeight,
  },
  body1Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.body.body1.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.body.body1.lineHeight,
  },
  body1Medium: {
    fontFamily: foundationTypography.fontFamily.latoMedium,
    fontSize: baseTypographyToken.body.body1.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightMedium as FontWeight,
    lineHeight: baseTypographyToken.body.body1.lineHeight,
  },
  body1Regular: {
    fontFamily: foundationTypography.fontFamily.latoRegular,
    fontSize: baseTypographyToken.body.body1.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightRegular as FontWeight,
    lineHeight: baseTypographyToken.body.body1.lineHeight,
  },
  body2Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.body.body2.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.body.body2.lineHeight,
  },
  body2Medium: {
    fontFamily: foundationTypography.fontFamily.latoMedium,
    fontSize: baseTypographyToken.body.body2.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightMedium as FontWeight,
    lineHeight: baseTypographyToken.body.body2.lineHeight,
  },
  body2Regular: {
    fontFamily: foundationTypography.fontFamily.latoRegular,
    fontSize: baseTypographyToken.body.body2.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightRegular as FontWeight,
    lineHeight: baseTypographyToken.body.body2.lineHeight,
  },
  body3Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.body.body3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.body.body3.lineHeight,
  },
  body3Medium: {
    fontFamily: foundationTypography.fontFamily.latoMedium,
    fontSize: baseTypographyToken.body.body3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightMedium as FontWeight,
    lineHeight: baseTypographyToken.body.body3.lineHeight,
  },
  body3Regular: {
    fontFamily: foundationTypography.fontFamily.latoRegular,
    fontSize: baseTypographyToken.body.body3.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightRegular as FontWeight,
    lineHeight: baseTypographyToken.body.body3.lineHeight,
  },
  body4Bold: {
    fontFamily: foundationTypography.fontFamily.latoBold,
    fontSize: baseTypographyToken.body.body4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightBold as FontWeight,
    lineHeight: baseTypographyToken.body.body4.lineHeight,
  },
  body4Medium: {
    fontFamily: foundationTypography.fontFamily.latoMedium,
    fontSize: baseTypographyToken.body.body4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightMedium as FontWeight,
    lineHeight: baseTypographyToken.body.body4.lineHeight,
  },
  body4Regular: {
    fontFamily: foundationTypography.fontFamily.latoRegular,
    fontSize: baseTypographyToken.body.body4.fontSize,
    fontWeight: foundationTypography.fontWeight.fontWeightRegular as FontWeight,
    lineHeight: baseTypographyToken.body.body4.lineHeight,
  },
};
